query_display: false
query_sort: 0
execution: 5
api_url: api.drupal.org
timer: 0
memory: 0
redirect_page: 0
page_alter: false
raw_names: false
error_handlers:
  1: 1
krumo_skin: default
rebuild_theme_registry: false
use_uncompressed_jquery: false
debug_mail_file_format: '%to-%subject-%datetime.mail.txt'
debug_mail_directory: 'temporary://devel-mails'
